include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true
    unnecessary_new: true
    prefer_single_quotes: true
    avoid_print: true
    curly_braces_in_flow_control_structures: true
    prefer_final_fields: true
    prefer_final_locals: true
    
    # Error prevention
    avoid_returning_null_for_void: true
    cancel_subscriptions: true
    close_sinks: true
    valid_regexps: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    missing_return: error