// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton/test/presentation/pages/tv/home_tv_series_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:ditonton/domain/usecases/tv/get_on_the_air_tv_series.dart'
    as _i2;
import 'package:ditonton/domain/usecases/tv/get_popular_tv_series.dart' as _i4;
import 'package:ditonton/domain/usecases/tv/get_top_rated_tv_series.dart'
    as _i6;
import 'package:ditonton/presentation/bloc/tv/on_the_air_tv_series/on_the_air_tv_series_bloc.dart'
    as _i3;
import 'package:ditonton/presentation/bloc/tv/popular_tv_series/popular_tv_series_bloc.dart'
    as _i5;
import 'package:ditonton/presentation/bloc/tv/top_rated_tv_series/top_rated_tv_series_bloc.dart'
    as _i7;
import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetOnTheAirTVSeries_0 extends _i1.SmartFake
    implements _i2.GetOnTheAirTVSeries {
  _FakeGetOnTheAirTVSeries_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOnTheAirTvSeriesState_1 extends _i1.SmartFake
    implements _i3.OnTheAirTvSeriesState {
  _FakeOnTheAirTvSeriesState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTVSeries_2 extends _i1.SmartFake
    implements _i4.GetPopularTVSeries {
  _FakeGetPopularTVSeries_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePopularTvSeriesState_3 extends _i1.SmartFake
    implements _i5.PopularTvSeriesState {
  _FakePopularTvSeriesState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTVSeries_4 extends _i1.SmartFake
    implements _i6.GetTopRatedTVSeries {
  _FakeGetTopRatedTVSeries_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopRatedTvSeriesState_5 extends _i1.SmartFake
    implements _i7.TopRatedTvSeriesState {
  _FakeTopRatedTvSeriesState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OnTheAirTvSeriesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnTheAirTvSeriesBloc extends _i1.Mock
    implements _i3.OnTheAirTvSeriesBloc {
  MockOnTheAirTvSeriesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetOnTheAirTVSeries get getOnTheAirTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#getOnTheAirTvSeries),
            returnValue: _FakeGetOnTheAirTVSeries_0(
              this,
              Invocation.getter(#getOnTheAirTvSeries),
            ),
          )
          as _i2.GetOnTheAirTVSeries);

  @override
  _i3.OnTheAirTvSeriesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeOnTheAirTvSeriesState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.OnTheAirTvSeriesState);

  @override
  _i8.Stream<_i3.OnTheAirTvSeriesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i3.OnTheAirTvSeriesState>.empty(),
          )
          as _i8.Stream<_i3.OnTheAirTvSeriesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i3.OnTheAirTvSeriesEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.OnTheAirTvSeriesEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.OnTheAirTvSeriesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.OnTheAirTvSeriesEvent>(
    _i9.EventHandler<E, _i3.OnTheAirTvSeriesState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i9.Transition<_i3.OnTheAirTvSeriesEvent, _i3.OnTheAirTvSeriesState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i3.OnTheAirTvSeriesEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onChange(_i9.Change<_i3.OnTheAirTvSeriesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PopularTvSeriesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTvSeriesBloc extends _i1.Mock
    implements _i5.PopularTvSeriesBloc {
  MockPopularTvSeriesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GetPopularTVSeries get getPopularTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularTvSeries),
            returnValue: _FakeGetPopularTVSeries_2(
              this,
              Invocation.getter(#getPopularTvSeries),
            ),
          )
          as _i4.GetPopularTVSeries);

  @override
  _i5.PopularTvSeriesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePopularTvSeriesState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.PopularTvSeriesState);

  @override
  _i8.Stream<_i5.PopularTvSeriesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i5.PopularTvSeriesState>.empty(),
          )
          as _i8.Stream<_i5.PopularTvSeriesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i5.PopularTvSeriesEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i5.PopularTvSeriesEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.PopularTvSeriesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i5.PopularTvSeriesEvent>(
    _i9.EventHandler<E, _i5.PopularTvSeriesState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i9.Transition<_i5.PopularTvSeriesEvent, _i5.PopularTvSeriesState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i5.PopularTvSeriesEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onChange(_i9.Change<_i5.PopularTvSeriesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedTvSeriesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvSeriesBloc extends _i1.Mock
    implements _i7.TopRatedTvSeriesBloc {
  MockTopRatedTvSeriesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetTopRatedTVSeries get getTopRatedTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTvSeries),
            returnValue: _FakeGetTopRatedTVSeries_4(
              this,
              Invocation.getter(#getTopRatedTvSeries),
            ),
          )
          as _i6.GetTopRatedTVSeries);

  @override
  _i7.TopRatedTvSeriesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTopRatedTvSeriesState_5(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i7.TopRatedTvSeriesState);

  @override
  _i8.Stream<_i7.TopRatedTvSeriesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i7.TopRatedTvSeriesState>.empty(),
          )
          as _i8.Stream<_i7.TopRatedTvSeriesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i7.TopRatedTvSeriesEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i7.TopRatedTvSeriesEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i7.TopRatedTvSeriesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i7.TopRatedTvSeriesEvent>(
    _i9.EventHandler<E, _i7.TopRatedTvSeriesState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i9.Transition<_i7.TopRatedTvSeriesEvent, _i7.TopRatedTvSeriesState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i7.TopRatedTvSeriesEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onChange(_i9.Change<_i7.TopRatedTvSeriesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
