// Mocks generated by Mockito 5.4.4 from annotations
// in ditonton/test/presentation/pages/tv/tv_series_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:ditonton/domain/usecases/tv/get_tv_series_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/tv/get_tv_series_recommendations.dart'
    as _i7;
import 'package:ditonton/domain/usecases/tv/get_watchlist_tv_series.dart'
    as _i9;
import 'package:ditonton/domain/usecases/tv/get_watchlist_tv_series_status.dart'
    as _i3;
import 'package:ditonton/domain/usecases/tv/remove_watchlist_tv_series.dart'
    as _i5;
import 'package:ditonton/domain/usecases/tv/save_watchlist_tv_series.dart'
    as _i4;
import 'package:ditonton/presentation/bloc/tv/tv_series_detail/tv_series_detail_bloc.dart'
    as _i6;
import 'package:ditonton/presentation/bloc/tv/tv_series_recommendations/tv_series_recommendations_bloc.dart'
    as _i8;
import 'package:ditonton/presentation/bloc/tv/watchlist_tv_series/watchlist_tv_series_bloc.dart'
    as _i10;
import 'package:flutter_bloc/flutter_bloc.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTVSeriesDetail_0 extends _i1.SmartFake
    implements _i2.GetTVSeriesDetail {
  _FakeGetTVSeriesDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchListTVSeriesStatus_1 extends _i1.SmartFake
    implements _i3.GetWatchListTVSeriesStatus {
  _FakeGetWatchListTVSeriesStatus_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchlistTVSeries_2 extends _i1.SmartFake
    implements _i4.SaveWatchlistTVSeries {
  _FakeSaveWatchlistTVSeries_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchlistTVSeries_3 extends _i1.SmartFake
    implements _i5.RemoveWatchlistTVSeries {
  _FakeRemoveWatchlistTVSeries_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesDetailState_4 extends _i1.SmartFake
    implements _i6.TvSeriesDetailState {
  _FakeTvSeriesDetailState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTVSeriesRecommendations_5 extends _i1.SmartFake
    implements _i7.GetTVSeriesRecommendations {
  _FakeGetTVSeriesRecommendations_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesRecommendationsState_6 extends _i1.SmartFake
    implements _i8.TvSeriesRecommendationsState {
  _FakeTvSeriesRecommendationsState_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchlistTVSeries_7 extends _i1.SmartFake
    implements _i9.GetWatchlistTVSeries {
  _FakeGetWatchlistTVSeries_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWatchlistTvSeriesState_8 extends _i1.SmartFake
    implements _i10.WatchlistTvSeriesState {
  _FakeWatchlistTvSeriesState_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvSeriesDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDetailBloc extends _i1.Mock
    implements _i6.TvSeriesDetailBloc {
  MockTvSeriesDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTVSeriesDetail get getTvSeriesDetail => (super.noSuchMethod(
        Invocation.getter(#getTvSeriesDetail),
        returnValue: _FakeGetTVSeriesDetail_0(
          this,
          Invocation.getter(#getTvSeriesDetail),
        ),
      ) as _i2.GetTVSeriesDetail);

  @override
  _i3.GetWatchListTVSeriesStatus get getWatchlistTvSeriesStatus =>
      (super.noSuchMethod(
        Invocation.getter(#getWatchlistTvSeriesStatus),
        returnValue: _FakeGetWatchListTVSeriesStatus_1(
          this,
          Invocation.getter(#getWatchlistTvSeriesStatus),
        ),
      ) as _i3.GetWatchListTVSeriesStatus);

  @override
  _i4.SaveWatchlistTVSeries get saveWatchlistTvSeries => (super.noSuchMethod(
        Invocation.getter(#saveWatchlistTvSeries),
        returnValue: _FakeSaveWatchlistTVSeries_2(
          this,
          Invocation.getter(#saveWatchlistTvSeries),
        ),
      ) as _i4.SaveWatchlistTVSeries);

  @override
  _i5.RemoveWatchlistTVSeries get removeWatchlistTvSeries =>
      (super.noSuchMethod(
        Invocation.getter(#removeWatchlistTvSeries),
        returnValue: _FakeRemoveWatchlistTVSeries_3(
          this,
          Invocation.getter(#removeWatchlistTvSeries),
        ),
      ) as _i5.RemoveWatchlistTVSeries);

  @override
  _i6.TvSeriesDetailState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeTvSeriesDetailState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.TvSeriesDetailState);

  @override
  _i11.Stream<_i6.TvSeriesDetailState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i11.Stream<_i6.TvSeriesDetailState>.empty(),
      ) as _i11.Stream<_i6.TvSeriesDetailState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i6.TvSeriesDetailEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i6.TvSeriesDetailEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i6.TvSeriesDetailState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i6.TvSeriesDetailEvent>(
    _i12.EventHandler<E, _i6.TvSeriesDetailState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i12.Transition<_i6.TvSeriesDetailEvent, _i6.TvSeriesDetailState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i6.TvSeriesDetailEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void onChange(_i12.Change<_i6.TvSeriesDetailState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TvSeriesRecommendationsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRecommendationsBloc extends _i1.Mock
    implements _i8.TvSeriesRecommendationsBloc {
  MockTvSeriesRecommendationsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.GetTVSeriesRecommendations get getTvSeriesRecommendations =>
      (super.noSuchMethod(
        Invocation.getter(#getTvSeriesRecommendations),
        returnValue: _FakeGetTVSeriesRecommendations_5(
          this,
          Invocation.getter(#getTvSeriesRecommendations),
        ),
      ) as _i7.GetTVSeriesRecommendations);

  @override
  _i8.TvSeriesRecommendationsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeTvSeriesRecommendationsState_6(
          this,
          Invocation.getter(#state),
        ),
      ) as _i8.TvSeriesRecommendationsState);

  @override
  _i11.Stream<_i8.TvSeriesRecommendationsState> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i11.Stream<_i8.TvSeriesRecommendationsState>.empty(),
      ) as _i11.Stream<_i8.TvSeriesRecommendationsState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i8.TvSeriesRecommendationsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i8.TvSeriesRecommendationsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i8.TvSeriesRecommendationsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i8.TvSeriesRecommendationsEvent>(
    _i12.EventHandler<E, _i8.TvSeriesRecommendationsState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i12.Transition<_i8.TvSeriesRecommendationsEvent,
                  _i8.TvSeriesRecommendationsState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i8.TvSeriesRecommendationsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void onChange(_i12.Change<_i8.TvSeriesRecommendationsState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WatchlistTvSeriesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistTvSeriesBloc extends _i1.Mock
    implements _i10.WatchlistTvSeriesBloc {
  MockWatchlistTvSeriesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.GetWatchlistTVSeries get getWatchlistTvSeries => (super.noSuchMethod(
        Invocation.getter(#getWatchlistTvSeries),
        returnValue: _FakeGetWatchlistTVSeries_7(
          this,
          Invocation.getter(#getWatchlistTvSeries),
        ),
      ) as _i9.GetWatchlistTVSeries);

  @override
  _i10.WatchlistTvSeriesState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeWatchlistTvSeriesState_8(
          this,
          Invocation.getter(#state),
        ),
      ) as _i10.WatchlistTvSeriesState);

  @override
  _i11.Stream<_i10.WatchlistTvSeriesState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i11.Stream<_i10.WatchlistTvSeriesState>.empty(),
      ) as _i11.Stream<_i10.WatchlistTvSeriesState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i10.WatchlistTvSeriesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i10.WatchlistTvSeriesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i10.WatchlistTvSeriesState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i10.WatchlistTvSeriesEvent>(
    _i12.EventHandler<E, _i10.WatchlistTvSeriesState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i12.Transition<_i10.WatchlistTvSeriesEvent,
                  _i10.WatchlistTvSeriesState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i10.WatchlistTvSeriesEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void onChange(_i12.Change<_i10.WatchlistTvSeriesState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
